package com.khuzz.software.jazirapro.coran

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import com.github.barteksc.pdfviewer.PDFView
import com.khuzz.software.jazirapro.R

class JuzzViewer : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_juzz_viewer)

        val juzzPdfView = findViewById<PDFView>(R.id.juzz_pdf_viewer)

        val intent = intent

        val juzz_position = intent.getIntExtra("juzz_position", 0)

        if (juzz_position == 0) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(0)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .load()
        } else if (juzz_position == 1) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(19)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .load()
        } else if (juzz_position == 2) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(37)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (juzz_position == 3) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(55)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (juzz_position == 4) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(72)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (juzz_position == 5) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(91)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (juzz_position == 6) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(108)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (juzz_position == 7) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(127)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (juzz_position == 8) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(145)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (juzz_position == 9) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(163)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (juzz_position == 10) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(180)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (juzz_position == 11) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(199)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (juzz_position == 12) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(218)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (juzz_position == 13) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(236)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (juzz_position == 14) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(254)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (juzz_position == 15) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(273)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (juzz_position == 16) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(293)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (juzz_position == 17) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(310)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (juzz_position == 18) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(330)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (juzz_position == 19) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(349)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (juzz_position == 20) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(367)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (juzz_position == 21) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(386)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (juzz_position == 22) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(405)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (juzz_position == 23) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(425)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (juzz_position == 24) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(443)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (juzz_position == 25) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(463)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (juzz_position == 26) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(482)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (juzz_position == 27) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(503)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (juzz_position == 28) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(523)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        }
        else if (juzz_position == 29) {
            juzzPdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(544)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        }
    }
}