package com.khuzz.software.jazirapro.coran

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import com.khuzz.software.jazirapro.R

class SouratesViewer : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_sourates_viewer)

        val pdfView = findViewById<PDFView>(R.id.sourates_pdf_viewer)

        val intent = intent
        val sourate_position = intent.getIntExtra("sourate_position", 0)

        if (sourate_position == 0) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(0)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .load()
        } else if (sourate_position == 1) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(1)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .load()
        } else if (sourate_position == 2) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(44)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 3) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(68)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 4) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(94)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 5) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(113)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 6) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(135)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 7) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(159)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 8) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(168)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 9) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(186)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 10) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(198)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 11) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(211)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 12) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(224)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 13) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(230)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 14) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(236)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 15) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(241)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 16) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(254)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 17) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(265)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 18) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(276)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 19) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(283)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 20) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(293)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 21) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(301)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 22) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(310)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 23) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(318)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 24) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(328)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 25) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(334)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 26) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(344)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 27) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(353)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 28) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(363)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 29) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(370)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 30) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(376)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 31) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(380)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 32) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(382)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 33) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(392)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 34) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(398)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 35) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(403)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 36) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(409)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 37) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(416)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 38) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(421)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 39) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(430)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 40) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(438)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 41) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(444)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 42) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(450)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 43) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(456)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 44) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(459)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 45) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(463)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 46) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(467)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 47) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(471)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 48) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(476)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 49) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(478)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 50) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(481)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 51) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(484)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 52) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(486)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 53) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(489)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 54) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(492)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 55) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(495)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 56) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(498)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 57) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(503)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 58) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(506)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 59) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(509)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 60) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(512)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 61) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(514)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 62) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(515)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 63) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(517)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 64) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(519)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 65) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(521)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 66) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(523)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 67) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(525)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 68) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(528)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 69) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(530)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 70) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(532)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 71) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(533)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 72) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(536)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 73) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(537)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 74) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(539)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 75) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(541)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 76) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(543)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 77) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(544)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 78) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(546)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 79) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(547)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 80) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(549)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 81) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(550)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 82) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(551)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 83) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(552)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 84) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(553)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 85) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(554)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 86) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(555)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 87) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(555)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 88) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(556)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 89) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(558)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 90) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(558)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 91) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(559)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 92) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(560)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 93) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(560)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 94) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(561)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 95) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(561)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 96) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(562)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 97) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(562)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 98) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(563)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 99) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(563)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 100) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(564)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 101) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(564)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 102) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(565)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 103) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(565)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 104) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(565)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 105) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(566)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 106) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(566)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 107) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(566)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 108) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(567)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 109) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(567)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 110) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(567)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 111) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(568)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 112) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(568)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        } else if (sourate_position == 113) {
            pdfView.fromAsset("coran_default_book.pdf")
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(568)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .fitEachPage(true)
                .autoSpacing(false)
                .pageSnap(true)
                .pageFling(true)
                .load()
        }
    }
}